[package]
edition.workspace = true
license.workspace = true
name = "ceno_host"
version.workspace = true

[dependencies]
itertools.workspace = true
rkyv = { version = "0.8.9", features = ["unaligned"] }

[dev-dependencies]
rand.workspace = true
