[package]
categories.workspace = true
description = "Ceno runtime library"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "ceno_rt"
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
riscv = "0.12"
rkyv = { version = "0.8.9", default-features = false, features = ["alloc", "bytecheck"] }

# [dependencies.alloc]
# optional = true
