[package]
edition = "2021"
name = "examples"
resolver = "2"
version = "0.1.0"

[dependencies]
ceno_rt = { path = "../ceno_rt" }
rkyv = { version = "0.8.9", default-features = false, features = ["alloc", "bytecheck"] }
ceno_host = { path = "../ceno_host", default-features = false}
